// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZuW47iRHxNr5V6vZTIGDLBLRDa9Hox2w',
    appId: '1:37974253661:web:10fc212f7e5d81b01a6db4',
    messagingSenderId: '37974253661',
    projectId: 'fasum-app-6f46a',
    authDomain: 'fasum-app-6f46a.firebaseapp.com',
    storageBucket: 'fasum-app-6f46a.appspot.com',
    measurementId: 'G-2M2RZWKLPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCErVpybZi_wztVBosuMPZLvwkTrA9nxTc',
    appId: '1:37974253661:android:51fabdc2e91b76791a6db4',
    messagingSenderId: '37974253661',
    projectId: 'fasum-app-6f46a',
    storageBucket: 'fasum-app-6f46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0BhXVmBGyHgjNoQ_6cUFnMSQoSg-yFE',
    appId: '1:37974253661:ios:0dc66e92a740d3e31a6db4',
    messagingSenderId: '37974253661',
    projectId: 'fasum-app-6f46a',
    storageBucket: 'fasum-app-6f46a.appspot.com',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0BhXVmBGyHgjNoQ_6cUFnMSQoSg-yFE',
    appId: '1:37974253661:ios:6852969f2cb567fd1a6db4',
    messagingSenderId: '37974253661',
    projectId: 'fasum-app-6f46a',
    storageBucket: 'fasum-app-6f46a.appspot.com',
    iosBundleId: 'com.example.fasumApp.RunnerTests',
  );
}
